import type { Asset } from './types';

export const mockAssets: Asset[] = [
  {
    id: '1',
    name: 'Notebook Dell Inspiron',
    codeId: 'NTB-001',
    city: 'São Paulo',
    value: 4500.0,
    observation: 'Departamento de Marketing',
  },
  {
    id: '2',
    name: 'Monitor LG 27"',
    codeId: 'MON-002',
    city: 'Rio de Janeiro',
    value: 1200.0,
    observation: 'Equipe de Design',
  },
  {
    id: '3',
    name: 'Cadeira de Escritório Ergonômica',
    codeId: 'CAD-003',
    city: 'São Paulo',
    value: 800.0,
  },
  {
    id: '4',
    name: 'Projetor Epson PowerLite',
    codeId: 'PRJ-004',
    city: 'Belo Horizonte',
    value: 2500.0,
    observation: 'Sala de reuniões principal',
  },
  {
    id: '5',
    name: 'Impressora HP LaserJet',
    codeId: 'IMP-005',
    city: 'São Paulo',
    value: 1800.0,
    observation: 'Uso compartilhado',
  },
  {
    id: '6',
    name: 'Mesa de Reunião',
    codeId: 'MES-006',
    city: 'Rio de Janeiro',
    value: 1500.0,
  },
  {
    id: '7',
    name: 'Smartphone Samsung Galaxy S23',
    codeId: 'CEL-007',
    city: 'Curitiba',
    value: 3200.0,
    observation: 'Diretoria',
  },
    {
    id: '8',
    name: 'Notebook Apple MacBook Pro',
    codeId: 'NTB-008',
    city: 'Curitiba',
    value: 15000.0,
    observation: 'Valor muito acima da média para notebooks',
  },
  {
    id: '9',
    name: 'Servidor Dell PowerEdge',
    codeId: 'SRV-009',
    city: 'São Paulo',
    value: 25000.0,
    observation: 'Data Center',
  },
  {
    id: '10',
    name: 'Câmera Canon EOS R6',
    codeId: 'CAM-010',
    city: 'Rio de Janeiro',
    value: 18000.0,
    observation: 'Equipe de produção de vídeo',
  },
];
